# SuperLocalMemory V2 - Funding
# Created by Varun Pratap Bhardwaj

# GitHub Sponsors (Primary - works in India)
github: [varun369]

# Buy Me a Coffee (supports India via Payoneer)
buy_me_a_coffee: varunpratah

# PayPal (works globally)
custom: ["https://paypal.me/varunpratapbhardwaj"]
