# SuperLocalMemory V2 - Funding
# Created by Varun Pratap Bhardwaj

# GitHub Sponsors (Primary - 0% fees for individuals)
github: [varun369]

# Alternative platforms (backup options)
ko_fi: varunpratap
# buy_me_a_coffee: varunpratap
# polar: varun369

# Custom links
custom: ["https://github.com/varun369/SuperLocalMemoryV2"]
